version: '3.8'

services:
  api-gateway:
    build:
      context: .
      args:
        SERVICE_NAME: api-gateway
    ports:
      - '3000:3000'

  auth-service:
    build:
      context: .
      args:
        SERVICE_NAME: auth-service
    ports:
      - '3001:3001'
  catalog-service:
    build:
      context: .
      args:
        SERVICE_NAME: catalog-service
    ports:
      - '3002:3002'
  order-service:
    build:
      context: .
      args:
        SERVICE_NAME: order-service
    ports:
      - '3003:3003'
